# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StrongestSoldier(object):
    def setupUi(self, StrongestSoldier):
        StrongestSoldier.setObjectName("StrongestSoldier")
        StrongestSoldier.resize(800, 842)
        self.VOTENOW = QtWidgets.QLabel(parent=StrongestSoldier)
        self.VOTENOW.setGeometry(QtCore.QRect(250, 20, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic")
        font.setPointSize(20)
        self.VOTENOW.setFont(font)
        self.VOTENOW.setIndent(75)
        self.VOTENOW.setObjectName("VOTENOW")
        self.EagleLeft = QtWidgets.QLabel(parent=StrongestSoldier)
        self.EagleLeft.setGeometry(QtCore.QRect(-10, 0, 471, 161))
        self.EagleLeft.setText("")
        self.EagleLeft.setPixmap(QtGui.QPixmap("../American.jpg"))
        self.EagleLeft.setObjectName("EagleLeft")
        self.Eagleright = QtWidgets.QLabel(parent=StrongestSoldier)
        self.Eagleright.setGeometry(QtCore.QRect(510, 0, 291, 171))
        self.Eagleright.setText("")
        self.Eagleright.setPixmap(QtGui.QPixmap("../American2.jpg"))
        self.Eagleright.setObjectName("Eagleright")
        self.Votebutton = QtWidgets.QPushButton(parent=StrongestSoldier)
        self.Votebutton.setGeometry(QtCore.QRect(200, 580, 90, 29))
        self.Votebutton.setObjectName("Votebutton")
        self.ResultsButton = QtWidgets.QPushButton(parent=StrongestSoldier)
        self.ResultsButton.setGeometry(QtCore.QRect(520, 580, 90, 29))
        self.ResultsButton.setDefault(False)
        self.ResultsButton.setFlat(False)
        self.ResultsButton.setObjectName("ResultsButton")
        self.U = QtWidgets.QLineEdit(parent=StrongestSoldier)
        self.U.setGeometry(QtCore.QRect(290, 500, 231, 51))
        self.U.setObjectName("U")
        self.Candidates = QtWidgets.QLabel(parent=StrongestSoldier)
        self.Candidates.setGeometry(QtCore.QRect(310, 200, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Candidates.setFont(font)
        self.Candidates.setIndent(30)
        self.Candidates.setObjectName("Candidates")
        self.Jane = QtWidgets.QRadioButton(parent=StrongestSoldier)
        self.Jane.setGeometry(QtCore.QRect(150, 310, 111, 25))
        self.Jane.setObjectName("Jane")
        self.buttonGroup = QtWidgets.QButtonGroup(StrongestSoldier)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Jane)
        self.John = QtWidgets.QRadioButton(parent=StrongestSoldier)
        self.John.setGeometry(QtCore.QRect(550, 310, 111, 25))
        self.John.setObjectName("John")
        self.buttonGroup.addButton(self.John)
        self.Agatha = QtWidgets.QRadioButton(parent=StrongestSoldier)
        self.Agatha.setGeometry(QtCore.QRect(350, 310, 111, 25))
        self.Agatha.setObjectName("Agatha")
        self.buttonGroup.addButton(self.Agatha)
        self.textforuser = QtWidgets.QLabel(parent=StrongestSoldier)
        self.textforuser.setGeometry(QtCore.QRect(370, 520, 63, 20))
        self.textforuser.setText("")
        self.textforuser.setObjectName("textforuser")
        self.BTMButton = QtWidgets.QPushButton(parent=StrongestSoldier)
        self.BTMButton.setGeometry(QtCore.QRect(355, 640, 101, 29))
        self.BTMButton.setObjectName("BTMButton")
        self.Text = QtWidgets.QLabel(parent=StrongestSoldier)
        self.Text.setGeometry(QtCore.QRect(282, 430, 271, 20))
        self.Text.setText("")
        self.Text.setObjectName("Text")
        self.VoteWidget = QtWidgets.QWidget(parent=StrongestSoldier)
        self.VoteWidget.setGeometry(QtCore.QRect(150, 270, 521, 341))
        self.VoteWidget.setObjectName("VoteWidget")

        self.retranslateUi(StrongestSoldier)
        QtCore.QMetaObject.connectSlotsByName(StrongestSoldier)

    def retranslateUi(self, StrongestSoldier):
        _translate = QtCore.QCoreApplication.translate
        StrongestSoldier.setWindowTitle(_translate("StrongestSoldier", "StrongestSoldier"))
        self.VOTENOW.setText(_translate("StrongestSoldier", "VOTE NOW"))
        self.Votebutton.setText(_translate("StrongestSoldier", "Vote"))
        self.ResultsButton.setText(_translate("StrongestSoldier", "Results"))
        self.Candidates.setText(_translate("StrongestSoldier", "Candidates"))
        self.Jane.setText(_translate("StrongestSoldier", "Jane"))
        self.John.setText(_translate("StrongestSoldier", "John"))
        self.Agatha.setText(_translate("StrongestSoldier", "Agatha"))
        self.BTMButton.setText(_translate("StrongestSoldier", "Back to Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StrongestSoldier = QtWidgets.QWidget()
    ui = Ui_StrongestSoldier()
    ui.setupUi(StrongestSoldier)
    StrongestSoldier.show()
    sys.exit(app.exec())
